[package]
name = "rustchain_discord_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
poise="0.5.5"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
llm-chain = "0.12.0"
llm-chain-openai = "0.12.0"

